### PR TITLE
3.1.0

### PR DESCRIPTION
**Pull request by patr1ckm**
This is a small bump to R `3.6.0` and a small `civis-r` release `2.1.0`.

I deleted the environment variables in the image because they are not being maintained.

### CODE REVIEW

**Comment by elsander** [comment]
What do you mean by "not being maintained"? They look up to date to me.

**Comment by patr1ckm** [comment]
> They look up to date to me

You're right! There's really no harm.

**Comment by elsander** [comment]
I would be curious to know if anyone uses them! I've definitely used the version number in Python packages, but I don't find myself checking package versions within R very often. Probably because I find version number to be a more common source of bugs in Python than R :)

**Comment by elsander** [comment]
Hmm, how did it let you merge before I approved?

**Pull request merged**
